
--CRIANDO TABELA DO CANAL
CREATE TABLE Canal (
CanalId int Primary KEY,
Nome VARCHAR(150) NOT NULL,
ContagemInscritos INT DEFAULT 0,
DataCriacao DATETIME NOT NULL
)

-- CONFERINDO SE ATABELA FOI CRIADA CORRETAMENTE
SELECT * FROM Canal;

--CRIACAO DA TABELA VIDEO
CREATE TABLE video(
VideoId INT PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
Vizualizacoes INT DEFAULT 0,
Likes  INT DEFAULT 0,
Dislikes  INT DEFAULT 0,
Duracao INT NOT NULL,
CanalId INT FOREIGN KEY REFERENCES Canal(CanalId)
);

SELECT * FROM video;