-- EU QUERO UM NOME E A DATA DE CONTRATAÇÃO DE TODOS OS FUNCIONARIOS QUE FORAM CONTRATADOS NO MESMO ANO

SELECT A.firstname,A.hiredata,b.firstname,b.hiredate
FROM Employees A, Employees B
WHERE DATEPART(YEAR, a.hiredate) = DATEPART(YEAR,B.HIREDATE);