--ELA PERMITE QUE CRIE VARIOS CODIGOS IGUAIS QUE NAO PODEM SER NULOS MAS QUE NÃO PODEM SER REPETIDOS
CREATE TABLE CarteiraMorotista(
  Id int NOT NULL,
  Nome varchar(255) NOT NULL,
  Idade int CHECK(Idade >= 18)
  CodigoCNH int NOT NULL UNIQUE
)